// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jmfmfixgwitvyultuyle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImptZm1maXhnd2l0dnl1bHR1eWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTQzNjcsImV4cCI6MjA3MzU5MDM2N30.JbjnYrpTQBg6gOCXchkoj-rLwZZsu9o0mlj8_jioYno";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});